# $schema: https://git.sr.ht/~johnhamelink/hass-json-schema/blob/main/json-schemas/blueprint-automation.json
blueprint:
  domain: automation
  name: Notificaties
  input:
    message:
      name: "Bericht"
      selector: 
        text: 
    notify_vincent:
      name: Meld aan Vincent
      selector: 
        boolean: 
      default: true
    notify_chris:
      name: Meld aan Christine
      selector: 
        boolean: 
      default: true
    confirm_action:
      name: Uitvoeren actie
      selector: 
        text:
      default: Uitvoeren
    trigger:
      name: "trigger"
      selector: 
        trigger:
    actie:
      name: "Actie"
      description: "Actie om uit te voeren bij bevestiging"
      selector: 
        action:
 mode: restart
variables:
  notify_chris: !input notify_chris
  notify_vincent: !input notify_vincent
  
triggers: 
  - triggers: !input trigger


actions: 
 - if:
     - condition: template 
       value_template: "{{ states('notify_vincent') == true }}"
   then:
     - action: notify.mobile_app_iphone
       data:
         message: !input message
         data:
           actions:
             - action: "{{ 'CONFIRM_' ~ context.id }}"
               title: !input confirm_action
 - if:
     - condition: template 
       value_template: "{{ states('notify_chris') == true} }"
   then:
     - action: notify.mobile_app_iphone_christine
       data:
         message: !input message
         data:
           actions:
             - action: "{{ 'CONFIRM_' ~ context.id }}"
               title: !input confirm_action
 - wait_for_trigger: 
   - trigger: event
     event_type: mobile_app_notification_action
     event_data:
      action: "{{ 'CONFIRM_' ~ context.id }}"
 - sequence: !input actie
