# $schema: https://git.sr.ht/~johnhamelink/hass-json-schema/blob/main/json-schemas/blueprint-automation.json
blueprint:
  domain: automation
  name: Notificaties
  input:
    actie:
      name: "Actie"
      description: "Actie om uit te voeren bij bevestiging"
      selector: 
        action:
    trigger:
      name: "trigger"
      selector: 
        trigger:
  
triggers: 
  - trigger: !input trigger
    id: trigger
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: "{{ 'CONFIRM_' ~ context.id }}"


actions: 
 - condition: trigger
   id: trigger
  
 - action: notify.send_message
   target:
     entity_id: notify.iphone
   data:
     message: test

  
